# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Newfun
email: newfun.email@qq.com
description: > # this means to ignore newlines until "baseurl:"
  为什么要写博客,梦想、技术、热爱。或许是不想让自己闲着,闲下来是浪费时间浪费生命,毕竟几年后我们是要在美国见的,有人说不想出国的程序员不是好程序员,这句话我TM竟然信了。94年正青春。</br>专注于React Native、iOS开发，欢迎交流。
  </br>--newfun.上海.2016年3月6日
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
sina_username:  newfun
github_username:  newfun1994
image: "http://newfun1994.github.io/image"
# Build settings
markdown: kramdown
